info:
  contact: {}
paths:
  /api/products:
    get:
      consumes:
      - application/json
      description: Get all products
      operationId: get-products
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get Products
      tags:
      - Products
  /api/products/{id}:
    get:
      consumes:
      - application/json
      description: Get a product by ID
      operationId: get-product-by-id
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get Product By ID
      tags:
      - Products
  /api/sales:
    get:
      consumes:
      - application/json
      description: Get all sales
      operationId: get-sales
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get Sales
      tags:
      - Sales
  /api/sales/{id}:
    get:
      consumes:
      - application/json
      description: Get a sale by ID
      operationId: get-sale-by-id
      parameters:
      - description: Sale ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get Sale By ID
      tags:
      - Sales
  /api/users:
    get:
      consumes:
      - application/json
      description: Get all users
      operationId: get-users
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get Users
      tags:
      - Users
  /api/users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      operationId: get-user-by-id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get User By ID
      tags:
      - Users
  /sales/interval:
    get:
      consumes:
      - application/json
      description: Get sales data filtered by a time interval
      operationId: get-sales-date
      parameters:
      - description: Time Interval
        in: query
        name: interval
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            type: string
        "500":
          description: error
          schema:
            additionalProperties: true
            type: object
      summary: Get Sales by Interval
      tags:
      - Sales
swagger: "2.0"
